# Generated by Django 4.2.6 on 2023-10-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='accepted/'),
        ),
    ]
